name: Build and Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm i
      - run: npm test
      - name: build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./index.html
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
      - name: print artifact
        run: echo ls 

