name: Build and Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm i
      - run: npm test

