name: Build and Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.example.outputs.first}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm i
      - name: build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: final_artifact
          path: ./build
      - name: Produce a output
        id: example
        run: echo "first = Hello" >> "GITHUB_OUTPUT" ';'
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: final_artifact
      - name: print artifact
        run: ls 
      - name: print output
        run: echo ${{needs.build.outputs.project_name}}


