name: input variables
on: 
  workflow_dispatch:
    inputs:
      env_name:
        required: true
        type: choice
        options: 
        - monalisa
        - cschleiden

jobs:
    res:
        runs-on: ubuntu-latest
        steps:
            - name: output1
              run: echo $INPUT_ENV_NAME
            - name: output2
              run: echo $ENV_NAME
            - name: output3
              run: echo $env_name