name: input variables
on: 
  workflow_dispatch:
    inputs:
      env_name:
        required: true
        type: choice
        options: 
        - monalisa
        - cschleiden

jobs:
    res:
        runs-on: ubuntu-latest
        steps:
            - name: output1
              run: echo "1. $INPUT_ENV_NAME"
            - name: output2
              run: echo "2. $ENV_NAME"
            - name: output3
              run: echo "3. $env_name"