name: Test Echo Target Action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call the composite action
        uses: ./.github/actions/echo-target
        with:
          build-target: staging
